#
# Makefile for Phoenix-RTOS 3 device drivers
#
# IA32 options
#
# Copyright 2018 Phoenix Systems
#

CROSS ?= i386-pc-phoenix-

MKDEP = $(CROSS)gcc -MM
MKDEPFLAGS = $(CFLAGS)

CC = $(CROSS)gcc
CFLAGS += -O2 -g -Wall -Wstrict-prototypes -fomit-frame-pointer -fno-strength-reduce

AR = $(CROSS)ar
ARFLAGS = -r

LD = $(CROSS)ld
#LDFLAGS = -m elf_i386

OBJCOPY = $(CROSS)objcopy
OBJDUMP = $(CROSS)objdump

STRIP = $(CROSS)strip
